- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - static_vars/var.yaml

  tasks:
  - name: create a disk
    gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a network
    gcp_compute_network:
      name: "{{ network_name }}"
      auto_create_subnetworks: 'true'
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: network

  - name: create a address
    gcp_compute_address:
      name: address-instance
      region: us-central1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address

  - name: create a filestore instance
    gcp_filestore_instance:
      name: nfsshare
      zone: "{{ zone }}"
      tier: STANDARD
      file_shares:
      - capacity_gb: 2048
        name: NFSvol
      networks:
      - network: "{{ network_name }}"
        modes:
        - MODE_IPV4
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present

